format = """
$cmd_duration\
[](#1A1A1D)\
$os\
$username\
[ ](fg:#8C8C97 bg:#1A1A1D)\
$hostname\
[](fg:#1A1A1D)\
[](fg:#8C8C97)\
$directory\
[](fg:#8C8C97)\
${custom.directory_separator_not_git}\
${custom.directory_separator_git}\
$symbol($git_branch)\
$symbol( $git_commit$git_status$git_metrics$git_state)\
$line_break\
$character
"""

[fill]
symbol = " "

# Set to true to avoid a two-line prompt
[line_break]
disabled = false

# Set disabled to true when using a one-line prompt for more aesthetically pleasing results
[character]
success_symbol = '[](bold #8C8C97)'
error_symbol = '[](bold red)'
format = '$symbol '
disabled = false

# Disable the blank line at the start of the prompt
#add_newline = false

# You can also replace your username with a neat symbol like  or disable this
# and use the os module below
[username]
show_always = true
style_user = 'bg:#1A1A1D'
style_root = 'bg:#1A1A1D'
format = '[$user ](bold $style)'
disabled = false

[hostname]
ssh_only = true
trim_at = '.'
style = 'bg:#1A1A1D'
format = '[@$hostname ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = 'bold bg:#1A1A1D fg:#8C8C97'
disabled = false # disabled by default

[os.symbols]
Debian = " "
Arch = "  "

[directory]
style = 'bold bg:#8C8C97 fg:#1A1A1D'
format = '[ $path ]($style)'
truncation_length = 3
truncation_symbol = '…/'

[git_branch]
symbol = ''
style = 'bold #8C8C97'
format = '[ $symbol $branch ]($style)'

[git_metrics]
disabled = false

[package]
disabled = true # Enable to output the current working directory's package version
format = "[$symbol$version]($style) "
display_private = true

# Output the command duration if grather than min_time (seconds)
[cmd_duration]
min_time = 1_000
format = "[   $duration \n\n]($style)"
style = "yellow"

